### ISSUE TITLE
Get more anime data

### ISSUE THREAD

**Issue by taksumaki** [PolyMeilex/node-myanimelist#17]
How can I get more information about the anime to search? Is that the ones she shows me are very few, for example, I need the cover of the anime, but I only get her poster.

This is what I get for now, it seems very little in my opinion, any way to get more information?

```js
{
results: [
    {
      mal_id: 12059,
      url: 'https://myanimelist.net/anime/12059/Otome_Dori',
      image_url: 'https://cdn.myanimelist.net/images/anime/1613/103859.jpg?s=417999eb6c98ec135c231306483791cf',
      title: 'Otome Dori',
      airing: false,
      synopsis: "Although they aren't dating now, Okino Kazuki is confident that he’ll end up with his best friend Sakuragi Otome. They live happy lives, oblivious to the jealous looks they get from the other importan...",
      type: 'OVA',
      episodes: 2,
      score: 5.77,
      start_date: '2012-05-25T00:00:00+00:00',
      end_date: '2012-09-28T00:00:00+00:00',
      members: 14775,
      rated: 'Rx'
    }
  ],
}
```

**Comment by PolyMeilex** [comment]
As it is a jikan request it is limited to what is shown on: https://myanimelist.net/anime.php?q=otome%20dori&cat=anime

Jikan Doc: https://jikan.docs.apiary.io/#reference/0/search

**Comment by PolyMeilex** [comment]
If you have any ideas where we could get/scrap better search info feel free to suggest, node-mal is not strictly limited to using jikan
